# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: WebDesign-Animated

on:
  push:
    branches: [ master ]
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js Environment
      uses: actions/setup-node@v2-beta
      with:
        version: 12
        
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.1.0
      with:
          cmd: install
          
    - name: Creating Build
      run: yarn build
    
    - name: Installing Surge
      run: npm install -g surge
    
    - name: Deploying on Surge
      run: surge ./build  http://webdesignanimated_usman.surge.sh/ --token ${{secrets.SURGE_TOKEN}}
